version: '3.8'

services:
 web:
  build:
   context: .
  ports:
  - 8000:5000
  volumes:
  - ./:/app

 mysqldb:
  image: mysql:8.0
  ports:
  - 3306:3306
  environment:
  - MYSQL_ROOT_PASSWORD=p@assw0rd1
  volumes:
  - mysql:/../var/lib/mysql
  - mysql_config:/../etc/mysql

volumes:
  mysql:
  mysql_config: